### ISSUE TITLE
[BUG]: SCOOP_GH_TOKEN does not get respected

### ISSUE THREAD

**Issue by CEbbinghaus** [ScoopInstaller/GithubActions#17]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

none

### Expected/Current Behaviour

Expected behaviour is that checkver.ps1 uses the SCOOP_GH_TOKEN env variable to fetch remote packages that require authentication to get to

### Steps to Reproduce

```console
* Create Scoop bucket with Autoupdate
* Add package manifest for private repository
* Add Auto update actions workflow 
* Add SCOOP_GH_TOKEN to secrets and set it as Environment variable
* Run Workflow
```

### Possible Solution

Maybe the checkver.ps1 script doesn't properly work with CI environment variables?

### Scoop and Buckets Version

```console
Current Scoop version:
v0.2.4 - Released at 2022-08-08
```
```


### Scoop Config

```console
No config as this is a CI job
```

### PowerShell Version

```console
pwsh so Probably Powershell core 7
```

**Comment by niheaven** [comment]
Use `GITHUB_TOKEN` that mentioned in README.

https://github.com/ScoopInstaller/GithubActions#available-environment-variables

**Comment by CEbbinghaus** [comment]
Wrong token... the GITHUB_TOKEN is for the local repository but this is getting releases from other repositories. GITHUB_TOKEN is specified too its just that the SCOOP_GH_TOKEN Isn't.

```yaml
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

name: Updater
jobs:
  update:
    name: Auto Update
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Update Packages
      uses: ScoopInstaller/GithubActions@main
      env:
        SCOOP_GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
        THROW_ERROR: '0'

```
here is the workflow file for reference
